### ISSUE TITLE
The source of these files should be specified

### ISSUE THREAD

**Issue by bandithedoge** [BGforgeNet/Fallout2-HQ-music#8]
From what I was able to find, the music in this repo seems to come from the soundtrack CDs that Interplay used to distribute (which is the highest quality that's out there). Still, for the sake of record keeping, the actual source of these specific versions should be noted in the README.

**Comment by egornovivan** [comment]
I think need to add these links to the readme
https://vgmdb.net/album/1375
https://vgmdb.net/album/49220

___

Although those who know how to work with audio editors will understand what kind of release it is without additional mentions

**Comment by burner1024** [comment]
I'm not sure about the actual source, so it is what it is.
